version: "3"
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - back-tier
    depends_on:
      - db

  backend:
    build: ./backend
    image: livs-stack/backend
    ports:
      - 8081:8081
    networks:
      - back-tier
    depends_on:
      - db

networks:
  back-tier:

volumes:
  db-data:
