version: "3"
services:

  db:
    build: ./db
    environment:
      POSTGRES_USER: "livs"
      POSTGRES_PASSWORD: "livs"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - back-tier

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - back-tier
    depends_on:
      - db

  backend:
    build: ./backend
    env_file:
      - ./backend/.env.prod
    image: livs-stack/backend
    ports:
      - 8081:8081
    networks:
      - back-tier
    depends_on:
      - db

  assets:
    build: ./assets
    env_file:
      - ./assets/.env.prod
    image: livs-stack/assets
    ports:
      - 8082:8082
    networks:
      - front-tier

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.prod
    image: livs-stack/frontend
    ports:
      - 8083:8083
    networks:
      - back-tier
      - front-tier
    depends_on:
      - backend
      - assets

networks:
  back-tier:
  front-tier:

volumes:
  db-data:
