version: "3"
services:

  db:
    build: ./db
    environment:
      POSTGRES_USER: "livs"
      POSTGRES_PASSWORD: "livs"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/csv/:/csv/
    ports:
      - 5432:5432
    networks:
      - back-tier

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - back-tier
    depends_on:
      - db

networks:
  back-tier:

volumes:
  db-data:

