version: "3"
services:

  db:
    build: ./db
    environment:
      POSTGRES_USER: "livs"
      POSTGRES_PASSWORD: "livs"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - back-tier

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - back-tier
    depends_on:
      - db

  backend:
    build: ./backend
    environment:
      PG__HOST: db
      PG__PORT: 5432
      PG__USER: livs
      PG__PASSWORD: livs
      PG__DBNAME: livs
      PG__POOL__MAX_SIZE: 16
      PG__POOL__TIMEOUTS__WAIT__SECS: 5
      PG__POOL__TIMEOUTS__WAIT__NANOS: 0
      RUST_LOG: actix_web=info
    image: livs-stack/backend
    ports:
      - 8081:8081
    networks:
      - back-tier
    depends_on:
      - db

networks:
  back-tier:

volumes:
  db-data:
