const data = [
  {
    id: 1,
    isbn: 'LTJK3AK0F1WJ58035',
    author: 16,
    edition: 8,
    format: 1,
    language: 20,
    genre: 14,
    pages: 637,
    publisher: 1,
    summary:
      'Aperiam quibusdam labore occaecati ea enim vel autem quisquam id.\nVoluptas aliquid alias molestiae.\nPlaceat autem quae.\nAlias alias deserunt expedita rerum quisquam qui incidunt occaecati ea.\nEt nulla cupiditate veritatis.',
    title: 'Unspecified subluxation of left knee',
    year: 1905,
  },
  {
    id: 2,
    isbn: 'NBZDK7K5ZAA342706',
    author: 27,
    edition: 1,
    format: 2,
    language: 16,
    genre: 27,
    pages: 64,
    publisher: 29,
    summary: 'Quasi nulla voluptatibus soluta numquam maxime.',
    title: 'Striatonigral degeneration',
    year: 2017,
  },
  {
    id: 3,
    isbn: 'VR7XTKZ14JHD47342',
    author: 6,
    edition: 1,
    format: 3,
    language: 4,
    genre: 17,
    pages: 524,
    publisher: 14,
    summary: 'est',
    title: 'Syphilitic saddle nose',
    year: 1966,
  },
  {
    id: 4,
    isbn: '6RNPLK6SRHKY34150',
    author: 15,
    edition: 10,
    format: 4,
    language: 1,
    genre: 17,
    pages: 486,
    publisher: 30,
    summary:
      'Consectetur nemo facilis laudantium. Minus quis labore sapiente in qui voluptate doloribus a. Quidem sit autem consequatur itaque fugit. Consequatur autem minus sunt animi aut.\n \nQuia architecto sit quis sed similique ut ut. Quis sit impedit deserunt ab earum animi minus. Ipsum molestiae ut.\n \nQuia cupiditate ipsum soluta quo qui dolores. Dolore et quidem facilis consequuntur est et. Sequi maxime qui amet voluptas. Vitae sed voluptatibus. Sunt molestias et.',
    title: 'Subacute cutaneous lupus erythematosus',
    year: 1957,
  },
  {
    id: 5,
    isbn: 'CYX9E9RAKMWX51907',
    author: 46,
    edition: 2,
    format: 5,
    language: 20,
    genre: 17,
    pages: 475,
    publisher: 18,
    summary: 'Ratione voluptatum at tempora.',
    title: 'Laceration of dorsal artery of right foot',
    year: 1994,
  },
  {
    id: 6,
    isbn: 'WZ4KMG9GTYYD80197',
    author: 25,
    edition: 2,
    format: 6,
    language: 25,
    genre: 22,
    pages: 165,
    publisher: 39,
    summary: 'quaerat aut distinctio',
    title: 'Late syphilitic oculopathy',
    year: 1954,
  },
  {
    id: 7,
    isbn: 'MZS8MMLBRMJF61284',
    author: 2,
    edition: 2,
    format: 7,
    language: 11,
    genre: 16,
    pages: 373,
    publisher: 2,
    summary: 'occaecati',
    title: 'Familial chondrocalcinosis, elbow',
    year: 1919,
  },
  {
    id: 8,
    isbn: '8U5N0Z0RK0KE30949',
    author: 1,
    edition: 10,
    format: 8,
    language: 15,
    genre: 10,
    pages: 384,
    publisher: 4,
    summary:
      'Alias dicta laborum sed laboriosam architecto molestiae et. Quaerat beatae sed et. Sequi vel earum. Sint atque magnam eligendi sed rerum. Sit at saepe officia in accusamus numquam.\n \nSoluta aut soluta voluptatem soluta voluptas voluptate. Quibusdam velit velit dolore quo aperiam ad laboriosam eius est. Maiores et ipsum quas dicta alias amet. Atque aut animi. Sit mollitia assumenda pariatur.\n \nEt voluptatem quo recusandae in blanditiis non distinctio. Et et omnis consectetur facere perferendis. Asperiores esse fugiat alias nihil aspernatur nihil. Minima repellendus debitis eos optio est corrupti. Voluptas incidunt exercitationem est veritatis delectus est consequatur.',
    title:
      'Salter Harris Type III physeal fracture of upper end of humerus, left arm',
    year: 1993,
  },
  {
    id: 9,
    isbn: 'D4X9L94CCTJZ25398',
    author: 4,
    edition: 2,
    format: 9,
    language: 4,
    genre: 3,
    pages: 249,
    publisher: 32,
    summary: 'perspiciatis exercitationem nihil',
    title:
      'Salter Harris Type III physeal fracture of upper end of humerus, left arm',
    year: 1979,
  },
  {
    id: 10,
    isbn: 'PRZL9PBZW2VR57934',
    author: 9,
    edition: 1,
    format: 10,
    language: 3,
    genre: 24,
    pages: 505,
    publisher: 8,
    summary:
      'Saepe nobis inventore molestiae minus molestiae.\nQuia blanditiis minima dignissimos placeat et illum voluptatem.\nExcepturi enim odit quod occaecati in voluptatum.\nSed eum consequuntur aut harum distinctio consequatur.',
    title: 'Contact with hot household appliances',
    year: 1928,
  },
  {
    id: 11,
    isbn: 'N76PLHBWWFR050373',
    author: 37,
    edition: 1,
    format: 1,
    language: 16,
    genre: 27,
    pages: 225,
    publisher: 39,
    summary:
      'Doloribus voluptas culpa pariatur fugiat totam magnam. Minima minus vero. Dolorem pariatur in amet ut quis voluptatum ut corporis voluptas. Qui eos qui. Illum sunt est vel. Suscipit ut quo.',
    title: 'Other disorders of continuity of bone, right radius',
    year: 1981,
  },
  {
    id: 12,
    isbn: 'D2ZLHXB6GEHY57440',
    author: 6,
    edition: 10,
    format: 2,
    language: 14,
    genre: 28,
    pages: 92,
    publisher: 1,
    summary:
      'Amet perspiciatis ut voluptas placeat quos est. Quasi omnis accusantium sequi quibusdam blanditiis laboriosam earum voluptates voluptatibus. Sit sed quia est et recusandae ea. Est officia quod. Est expedita est voluptas quis quas nisi quas consequatur.\n \nFacere sed ab magnam totam minima voluptate expedita. Et dolorum accusantium. Blanditiis quis odio minus magnam eum. Rem cumque sapiente perspiciatis. Tempore dolores magnam qui distinctio debitis ut. Consequatur molestiae suscipit sunt ut itaque ipsam est qui.\n \nPossimus amet molestiae est quo sit error est alias. Voluptates perspiciatis optio et illo nemo. Animi qui aliquid sit in ullam repudiandae sed et. Officia quia sint. Cumque sed quibusdam eaque doloremque autem distinctio. Eveniet voluptas nostrum.',
    title:
      'Other specified injury of unspecified blood vessel at shoulder and upper arm level, right arm',
    year: 1998,
  },
  {
    id: 13,
    isbn: 'AUM76S2CKMT011595',
    author: 22,
    edition: 10,
    format: 3,
    language: 19,
    genre: 29,
    pages: 578,
    publisher: 42,
    summary:
      'Laboriosam quo et aliquid nihil quo. Distinctio velit suscipit modi nulla consequatur rerum. Sequi deserunt ut id iusto perspiciatis.',
    title: 'Varicose veins of left lower extremity with inflammation',
    year: 1984,
  },
  {
    id: 14,
    isbn: 'Z8NC8BC041WZ28919',
    author: 9,
    edition: 10,
    format: 4,
    language: 3,
    genre: 19,
    pages: 44,
    publisher: 20,
    summary: 'voluptas',
    title: 'Urethral caruncle',
    year: 1939,
  },
  {
    id: 15,
    isbn: 'JEBXZUE0ASGV99726',
    author: 23,
    edition: 3,
    format: 5,
    language: 17,
    genre: 1,
    pages: 410,
    publisher: 32,
    summary: 'Dicta repellat aut voluptas nisi iste non amet porro.',
    title: 'Disease of spleen, unspecified',
    year: 1928,
  },
  {
    id: 16,
    isbn: 'ZCLHS5S5T0HM95404',
    author: 19,
    edition: 1,
    format: 6,
    language: 12,
    genre: 20,
    pages: 554,
    publisher: 1,
    summary:
      'Laudantium quae sed et iusto voluptatum voluptatem et ab. Iure vel consequuntur omnis ut nihil. Repudiandae qui ut ut quaerat voluptate officia labore itaque mollitia. Sapiente illum veniam sint aut rerum dolores rem repudiandae. Voluptatibus veniam omnis animi possimus voluptas consequatur. Voluptas asperiores laboriosam quo perspiciatis quia quisquam nostrum non est.',
    title:
      'Corrosion of third degree of multiple sites of left wrist and hand',
    year: 1954,
  },
  {
    id: 17,
    isbn: '1LWBVKEGJKRM38660',
    author: 21,
    edition: 2,
    format: 7,
    language: 8,
    genre: 12,
    pages: 292,
    publisher: 41,
    summary:
      'Qui officiis aut dolorum distinctio nemo illum.\nEaque consequatur repellendus.\nDelectus voluptas doloremque id qui provident occaecati omnis in iusto.\nConsequuntur quo nisi alias modi illum.',
    title: 'Syphilitic saddle nose',
    year: 1952,
  },
  {
    id: 18,
    isbn: 'G6HWXFT083M196001',
    author: 20,
    edition: 9,
    format: 8,
    language: 13,
    genre: 30,
    pages: 39,
    publisher: 2,
    summary: 'Quis a eum.',
    title: 'Total perforations of tympanic membrane, right ear',
    year: 1936,
  },
  {
    id: 19,
    isbn: 'P1K6186RH0UX16116',
    author: 8,
    edition: 5,
    format: 9,
    language: 21,
    genre: 18,
    pages: 699,
    publisher: 19,
    summary:
      'Aspernatur voluptas earum id sequi ut et impedit quia laudantium. Sit earum saepe vel explicabo expedita. Molestias exercitationem dicta porro quae. Eaque quam nulla exercitationem corporis. Quas perspiciatis laudantium autem reprehenderit eum nulla odio.\n \nMaiores numquam corrupti voluptatum doloribus vero ipsam. Sint facere vitae. Architecto sequi consequatur illum veniam repellendus dolor doloribus rem. Quae ullam molestiae est consequatur labore.\n \nDolorem nam exercitationem fugit nam. Sequi ut itaque quia repellendus officia unde. Et ut in.',
    title: 'Toxic effect of other seafood, assault',
    year: 2012,
  },
  {
    id: 20,
    isbn: '393Y42S8R3SN66460',
    author: 1,
    edition: 7,
    format: 10,
    language: 19,
    genre: 17,
    pages: 134,
    publisher: 34,
    summary:
      'Delectus amet qui odit ad fugit. In numquam voluptates non eum corrupti. Voluptatibus ab reiciendis saepe explicabo quidem. Modi nisi modi dolorem rerum quisquam ea beatae. Deserunt iure reiciendis ut et.',
    title: 'Subacute osteomyelitis, right tibia and fibula',
    year: 1952,
  },
  {
    id: 21,
    isbn: 'JGTDABM3P0J557999',
    author: 17,
    edition: 2,
    format: 1,
    language: 16,
    genre: 15,
    pages: 388,
    publisher: 27,
    summary: 'nesciunt',
    title:
      'Traumatic rupture of unspecified ligament of right little finger at metacarpophalangeal and interphalangeal joint',
    year: 2008,
  },
  {
    id: 22,
    isbn: 'DCU03MS31SE348477',
    author: 7,
    edition: 1,
    format: 2,
    language: 15,
    genre: 19,
    pages: 577,
    publisher: 26,
    summary: 'itaque harum aut',
    title: 'Toxic effect of other seafood, assault',
    year: 1967,
  },
  {
    id: 23,
    isbn: '77RBWSCYY3HJ72514',
    author: 9,
    edition: 5,
    format: 3,
    language: 15,
    genre: 27,
    pages: 160,
    publisher: 40,
    summary:
      'Non ut praesentium et eos.\nOdit quibusdam eum cumque molestiae enim autem.',
    title: 'Other chronic hematogenous osteomyelitis, left humerus',
    year: 1981,
  },
  {
    id: 24,
    isbn: '8ZZ7X4HZPUYG51363',
    author: 27,
    edition: 6,
    format: 4,
    language: 12,
    genre: 12,
    pages: 57,
    publisher: 5,
    summary:
      'Ullam optio et nulla aperiam qui.\nLaudantium eligendi est quaerat perferendis pariatur illum eius nihil voluptas.',
    title: 'Corrosion of unspecified degree of right lower leg',
    year: 1981,
  },
  {
    id: 25,
    isbn: 'HDXRD9470NSJ79768',
    author: 21,
    edition: 10,
    format: 5,
    language: 1,
    genre: 2,
    pages: 280,
    publisher: 13,
    summary: 'Omnis rerum et laudantium dolorum ut.',
    title:
      'Unspecified occupant of military vehicle injured in nontraffic accident',
    year: 1922,
  },
  {
    id: 26,
    isbn: '9A2LE1XC64AW62400',
    author: 29,
    edition: 10,
    format: 6,
    language: 15,
    genre: 25,
    pages: 475,
    publisher: 23,
    summary: 'saepe',
    title: 'Rheumatoid bursitis, wrist',
    year: 2005,
  },
  {
    id: 27,
    isbn: 'TCJ2PTSE3EA513785',
    author: 12,
    edition: 9,
    format: 7,
    language: 17,
    genre: 13,
    pages: 604,
    publisher: 23,
    summary: 'debitis quos itaque',
    title:
      'Nondisplaced fracture of lateral condyle of unspecified femur',
    year: 2018,
  },
  {
    id: 28,
    isbn: 'DZPV2P84ZHSL27520',
    author: 8,
    edition: 10,
    format: 8,
    language: 14,
    genre: 3,
    pages: 24,
    publisher: 4,
    summary:
      'Maxime voluptatem aut esse qui possimus et. Est est ab quis ratione dolorem et quia est placeat. Eum deserunt molestias eum eaque molestiae sed.',
    title: 'Urethral caruncle',
    year: 1964,
  },
  {
    id: 29,
    isbn: 'BC616HLK7SZU36517',
    author: 6,
    edition: 2,
    format: 9,
    language: 21,
    genre: 14,
    pages: 360,
    publisher: 12,
    summary: 'Qui possimus amet debitis ut consectetur dolorem.',
    title:
      'School (private) (public) (state) as the place of occurrence of the external cause',
    year: 2002,
  },
  {
    id: 30,
    isbn: 'E7DD62CHBNW485541',
    author: 47,
    edition: 1,
    format: 10,
    language: 24,
    genre: 4,
    pages: 378,
    publisher: 17,
    summary: 'Totam voluptatem architecto ut.',
    title: 'Myocarditis, unspecified',
    year: 1906,
  },
  {
    id: 31,
    isbn: 'JF1VS5DAW5JS57119',
    author: 31,
    edition: 10,
    format: 1,
    language: 9,
    genre: 17,
    pages: 578,
    publisher: 29,
    summary: 'aut dolore quibusdam',
    title: 'Contusion of small intestine',
    year: 1962,
  },
  {
    id: 32,
    isbn: 'H1VG5D0PL6BD81738',
    author: 36,
    edition: 2,
    format: 2,
    language: 3,
    genre: 28,
    pages: 216,
    publisher: 3,
    summary:
      'Perspiciatis aperiam nostrum. Officia odio velit et perspiciatis dolor et ea rerum. Explicabo voluptatibus quis velit architecto cumque facilis quod sit.\n \nVoluptatem veritatis suscipit accusantium. Placeat cum omnis eius quas voluptatum quia. Ratione ut aut inventore aliquam. In voluptatem eos optio. Est odit praesentium cum eius eos sed nostrum impedit ex.\n \nSaepe voluptatem ducimus. Omnis quo perferendis. Dicta optio eos voluptatum nihil aut adipisci reprehenderit. Deleniti adipisci dolores.',
    title: 'Other complications of amputation stump',
    year: 1913,
  },
  {
    id: 33,
    isbn: '6386PTG1SWGW50592',
    author: 9,
    edition: 1,
    format: 3,
    language: 2,
    genre: 13,
    pages: 687,
    publisher: 4,
    summary: 'itaque',
    title: 'Edema of left upper eyelid',
    year: 2019,
  },
  {
    id: 34,
    isbn: '6KLNM01L8YJJ62158',
    author: 5,
    edition: 2,
    format: 4,
    language: 8,
    genre: 1,
    pages: 490,
    publisher: 14,
    summary: 'Labore voluptatem maiores.',
    title:
      'Unspecified fracture of fourth metacarpal bone, left hand',
    year: 1922,
  },
  {
    id: 35,
    isbn: 'PCAH7CU4K7E550099',
    author: 15,
    edition: 8,
    format: 5,
    language: 4,
    genre: 14,
    pages: 264,
    publisher: 32,
    summary: 'Error quasi itaque.',
    title:
      'Unspecified injury of extensor muscle, fascia and tendon of right little finger at forearm level',
    year: 1990,
  },
  {
    id: 36,
    isbn: 'FS13RUMYX7WM10343',
    author: 37,
    edition: 1,
    format: 6,
    language: 15,
    genre: 13,
    pages: 436,
    publisher: 1,
    summary:
      'Et sapiente vitae quidem inventore pariatur ut. Consequuntur est ut. Nihil dolorem iste et ipsam qui nam consequuntur. Atque sequi suscipit ea.',
    title: 'Other pneumothorax and air leak',
    year: 1965,
  },
  {
    id: 37,
    isbn: 'Z4H6SAAZB7C326585',
    author: 25,
    edition: 1,
    format: 7,
    language: 15,
    genre: 26,
    pages: 234,
    publisher: 16,
    summary:
      'Voluptatem impedit incidunt ex molestiae laboriosam eos.\nAdipisci et iste molestiae adipisci magnam saepe.\nError deleniti itaque illum eaque fuga est.\nEt ullam rerum aspernatur tempora aut voluptas voluptatum dolorem adipisci.',
    title:
      'Encounter for aftercare following multiple organ transplant',
    year: 1979,
  },
  {
    id: 38,
    isbn: '6982T89D42NL83657',
    author: 20,
    edition: 2,
    format: 8,
    language: 23,
    genre: 3,
    pages: 463,
    publisher: 18,
    summary:
      'Delectus expedita voluptate. Aut corporis animi voluptatem. Debitis explicabo perspiciatis quia facere autem consequatur dignissimos aut ullam. Id soluta saepe aut sit non cumque omnis. Modi aut modi qui fuga delectus et rerum distinctio.\n \nInventore ut blanditiis atque aut. Voluptas id adipisci cupiditate vitae harum laudantium rem. Rerum iure quis neque. Quibusdam unde et.\n \nOmnis voluptatem earum praesentium blanditiis. Dolor voluptas in. Iusto modi ut omnis.',
    title: 'Chondrolysis, hip',
    year: 1926,
  },
  {
    id: 39,
    isbn: '1NRN7VDCW0YF73993',
    author: 21,
    edition: 7,
    format: 9,
    language: 18,
    genre: 24,
    pages: 172,
    publisher: 3,
    summary:
      'Ab corrupti enim adipisci. Quia quae sunt omnis voluptas. Nam vero ut tempore molestiae molestiae unde fugit id. Ullam mollitia beatae et impedit sint perferendis optio repudiandae. Dolorem asperiores doloremque non quia qui suscipit.',
    title:
      'Salter-Harris Type I physeal fracture of upper end of unspecified femur',
    year: 1973,
  },
  {
    id: 40,
    isbn: '0VF90ZF2NDV822140',
    author: 50,
    edition: 1,
    format: 10,
    language: 12,
    genre: 31,
    pages: 161,
    publisher: 41,
    summary:
      'Incidunt illum debitis at aperiam est ex illo mollitia aspernatur.\nExpedita dolor sed non vel dicta cum est voluptatem aspernatur.\nEt ea similique id optio laudantium qui sint ipsum veniam.',
    title:
      'Benign neoplasm of connective and other soft tissue of lower limb, including hip',
    year: 2002,
  },
  {
    id: 41,
    isbn: 'FW9S8WWVVXJ281002',
    author: 47,
    edition: 10,
    format: 1,
    language: 3,
    genre: 7,
    pages: 684,
    publisher: 43,
    summary:
      'Molestias sit blanditiis tempore minus ea et corporis ea. Similique et consectetur sunt quasi. Voluptas mollitia tenetur voluptatem nihil quaerat. Perferendis consequatur reprehenderit rerum officia dolor. Hic et perspiciatis delectus sint quia. Eos quia illo magnam molestiae consectetur accusamus omnis.',
    title:
      'Malignant neoplasm of other and unspecified female genital organs',
    year: 1995,
  },
  {
    id: 42,
    isbn: '8BRR54CNMSDP50492',
    author: 7,
    edition: 4,
    format: 2,
    language: 1,
    genre: 1,
    pages: 639,
    publisher: 37,
    summary:
      'Hic porro amet illo dolor cupiditate occaecati dignissimos porro. Cumque a veritatis autem inventore veritatis sit unde neque. Rerum pariatur ab vel est enim. Est autem quia. Dolorum voluptatem nemo excepturi reiciendis blanditiis. Sed mollitia labore odit nihil consequatur doloremque iure enim soluta.',
    title: 'Contact with turtles',
    year: 1949,
  },
  {
    id: 43,
    isbn: 'WTHPUXTNJRW647957',
    author: 45,
    edition: 1,
    format: 3,
    language: 24,
    genre: 13,
    pages: 606,
    publisher: 24,
    summary: 'quibusdam aspernatur reprehenderit',
    title: 'Chronic myeloid leukemia, BCR/ABL-positive, in remission',
    year: 1936,
  },
  {
    id: 44,
    isbn: 'RVRXHAMXDCER53210',
    author: 12,
    edition: 5,
    format: 4,
    language: 7,
    genre: 30,
    pages: 336,
    publisher: 6,
    summary: 'aut corporis soluta',
    title: 'Total perforations of tympanic membrane, right ear',
    year: 1973,
  },
  {
    id: 45,
    isbn: 'DE643HPGAFJ240128',
    author: 22,
    edition: 10,
    format: 5,
    language: 25,
    genre: 26,
    pages: 615,
    publisher: 8,
    summary:
      'Expedita voluptas facere. Eum ipsam voluptatum asperiores ut distinctio nisi. Facere facere alias et.\n \nMaiores quos enim est explicabo ipsam. Provident ea libero neque expedita placeat vitae. Aut iste placeat nulla et facere sit beatae voluptate.\n \nEt velit et voluptas est et voluptatem repellendus. Est porro natus laborum nesciunt ipsum nisi ut. Architecto maiores illo magni. Nam fuga natus a sunt cum cum doloribus. Soluta repellendus delectus est consequatur quis nesciunt sed est.',
    title: 'Acute tonsillitis, unspecified',
    year: 1926,
  },
  {
    id: 46,
    isbn: 'WFAKP94MMBP546857',
    author: 20,
    edition: 3,
    format: 6,
    language: 11,
    genre: 9,
    pages: 235,
    publisher: 19,
    summary: 'unde',
    title:
      'Other specified injury of unspecified blood vessel at shoulder and upper arm level, right arm',
    year: 2015,
  },
  {
    id: 47,
    isbn: '11YWJ7ZPBCYE31269',
    author: 24,
    edition: 7,
    format: 7,
    language: 19,
    genre: 12,
    pages: 389,
    publisher: 6,
    summary:
      'Iste aut culpa iusto pariatur rerum vel. Minima accusantium qui numquam voluptas. Sint sunt nihil impedit odit libero. A autem minus. Nihil cum ex. Quidem ab tempore vel illo dignissimos ut et quia.',
    title: 'Other spotted fevers',
    year: 1952,
  },
  {
    id: 48,
    isbn: '0VF1MBT92UD298824',
    author: 12,
    edition: 2,
    format: 8,
    language: 11,
    genre: 8,
    pages: 396,
    publisher: 36,
    summary:
      'Modi ut aperiam odio. Nesciunt sit aperiam velit aut omnis qui. Eos occaecati asperiores aut et id facere. Voluptatem temporibus iste id quisquam non. Consequatur reiciendis ut aliquam. Labore laudantium expedita.',
    title:
      'Elevated blood-pressure reading, without diagnosis of hypertension',
    year: 1990,
  },
  {
    id: 49,
    isbn: 'N811SK2CJ1HM40295',
    author: 5,
    edition: 7,
    format: 9,
    language: 20,
    genre: 9,
    pages: 78,
    publisher: 38,
    summary:
      'Natus debitis quo expedita et praesentium nemo dolorum.',
    title: 'Late syphilitic oculopathy',
    year: 1920,
  },
  {
    id: 50,
    isbn: '9F03Y6AZA0GT90600',
    author: 16,
    edition: 7,
    format: 10,
    language: 1,
    genre: 19,
    pages: 388,
    publisher: 18,
    summary: 'ratione voluptatem nam',
    title:
      'Benign neoplasm of connective and other soft tissue of lower limb, including hip',
    year: 1904,
  },
  {
    id: 51,
    isbn: '8FHZ05SVDVPH70680',
    author: 36,
    edition: 4,
    format: 1,
    language: 3,
    genre: 28,
    pages: 405,
    publisher: 43,
    summary: 'Excepturi eos aut sed dolore.',
    title: "Swimmer's ear, left ear",
    year: 2020,
  },
  {
    id: 52,
    isbn: '6RU4JYXSTLCC33390',
    author: 40,
    edition: 2,
    format: 2,
    language: 2,
    genre: 24,
    pages: 465,
    publisher: 22,
    summary: 'Et quasi facere quae laborum nihil ut.',
    title: 'Burn of unspecified body region, unspecified degree',
    year: 1944,
  },
  {
    id: 53,
    isbn: '3BCXH8BAX3D520105',
    author: 50,
    edition: 3,
    format: 3,
    language: 9,
    genre: 20,
    pages: 150,
    publisher: 36,
    summary:
      'Eius omnis et. Dolor doloremque assumenda est velit temporibus. Velit voluptatem dolorem qui pariatur est minus dolores nobis modi. Sed eum itaque eum. Magnam sint consectetur nihil mollitia voluptatem vero minus.\n \nSequi asperiores mollitia quae qui expedita vel. Facilis quia illo dignissimos voluptate eum. Suscipit est repellendus maiores minima sunt reprehenderit itaque et non. Molestiae voluptas sequi sint. Doloremque laboriosam qui beatae. Nihil aliquid quia unde nulla quia suscipit.\n \nFuga expedita nisi animi et alias aut ipsam a. Harum qui nam enim sit ut. Voluptas quia accusamus officiis praesentium voluptatum accusantium asperiores est. Cumque sint quo quo magni omnis id quia. Laboriosam assumenda est enim. Quo assumenda ut et iure hic vel consequatur velit.',
    title: 'Other spondylosis',
    year: 1900,
  },
  {
    id: 54,
    isbn: '0AS3REKDJ6BG34934',
    author: 3,
    edition: 3,
    format: 4,
    language: 8,
    genre: 14,
    pages: 131,
    publisher: 4,
    summary: 'deserunt in corporis',
    title:
      'Inhalant use, unspecified with inhalant-induced psychotic disorder with hallucinations',
    year: 1991,
  },
  {
    id: 55,
    isbn: '6U8JUM84PFA076936',
    author: 43,
    edition: 7,
    format: 5,
    language: 17,
    genre: 29,
    pages: 58,
    publisher: 19,
    summary:
      'Similique odit eveniet ea quisquam omnis expedita. Harum veritatis aut. Et voluptatem qui consequatur fugiat iste saepe magnam ipsum qui. Eum ullam hic facere eos autem reiciendis expedita ut impedit. Odit possimus aut suscipit animi est sunt itaque corrupti.',
    title:
      'Laceration of flexor muscle, fascia and tendon of right index finger at forearm level',
    year: 1998,
  },
  {
    id: 56,
    isbn: 'SWDN162X81W043344',
    author: 31,
    edition: 5,
    format: 6,
    language: 16,
    genre: 16,
    pages: 69,
    publisher: 15,
    summary:
      'Eum eum iste debitis atque sed aut ipsa soluta molestias.',
    title: 'Rheumatoid bursitis, wrist',
    year: 1901,
  },
  {
    id: 57,
    isbn: '5WPBS30B4UBH23602',
    author: 16,
    edition: 6,
    format: 7,
    language: 9,
    genre: 5,
    pages: 210,
    publisher: 22,
    summary:
      'Dolorem ducimus autem consequatur quia magni. Eius repellat commodi magnam.',
    title: 'Other disorders of continuity of bone, right radius',
    year: 1906,
  },
  {
    id: 58,
    isbn: '20VBLM0NPHUF13284',
    author: 27,
    edition: 8,
    format: 8,
    language: 18,
    genre: 10,
    pages: 481,
    publisher: 8,
    summary: 'expedita commodi tempore',
    title: 'Acute mastoiditis without complications, unspecified ear',
    year: 2009,
  },
  {
    id: 59,
    isbn: 'AY5NGSVCHRXL20081',
    author: 5,
    edition: 2,
    format: 9,
    language: 26,
    genre: 27,
    pages: 408,
    publisher: 2,
    summary: 'Omnis est possimus.',
    title: 'Other acute osteomyelitis, right shoulder',
    year: 1918,
  },
  {
    id: 60,
    isbn: 'LS19ABELLGY049939',
    author: 8,
    edition: 4,
    format: 10,
    language: 20,
    genre: 23,
    pages: 473,
    publisher: 40,
    summary:
      'Eos aut accusamus exercitationem distinctio quia eos. Atque tenetur accusantium et et tempora sint modi temporibus. Eligendi quo odit blanditiis ducimus ea ut adipisci. Dolorum ut non quia nihil est occaecati mollitia vero. Quasi corporis beatae recusandae et quam dolores non et. Dolores unde non tenetur ad.',
    title: 'Cystic meniscus, anterior horn of medial meniscus',
    year: 1953,
  },
  {
    id: 61,
    isbn: 'TJ3BS50X1ZLK91493',
    author: 17,
    edition: 2,
    format: 1,
    language: 25,
    genre: 22,
    pages: 570,
    publisher: 35,
    summary: 'Eos tempora nemo recusandae magnam aut ipsum est.',
    title: 'Transient synovitis, hip',
    year: 1926,
  },
  {
    id: 62,
    isbn: 'BT1MY7AKVZZB34167',
    author: 34,
    edition: 10,
    format: 2,
    language: 6,
    genre: 18,
    pages: 203,
    publisher: 37,
    summary:
      'Eligendi necessitatibus assumenda sit.\nMolestias placeat sint aut error dignissimos omnis laudantium.\nSunt necessitatibus optio nesciunt eveniet dignissimos veniam enim perferendis.\nSoluta mollitia illo voluptas.\nVeniam nihil et soluta iste reprehenderit sunt dolores qui enim.',
    title: 'Acute hepatitis A',
    year: 1900,
  },
  {
    id: 63,
    isbn: 'CW8AD81A8YYJ65694',
    author: 5,
    edition: 6,
    format: 3,
    language: 5,
    genre: 2,
    pages: 303,
    publisher: 11,
    summary: 'dolores',
    title:
      'Exposure to smoke in uncontrolled fire in building or structure',
    year: 1986,
  },
  {
    id: 64,
    isbn: '2HAY1AMNDFGL83467',
    author: 36,
    edition: 7,
    format: 4,
    language: 13,
    genre: 12,
    pages: 666,
    publisher: 12,
    summary: 'ut unde voluptatem',
    title: "Meningitis in Chagas' disease",
    year: 1967,
  },
  {
    id: 65,
    isbn: 'RPNJPKBWAVJU11992',
    author: 12,
    edition: 9,
    format: 5,
    language: 6,
    genre: 21,
    pages: 193,
    publisher: 16,
    summary:
      'Consequatur vel in molestias dolor sed. Aut earum animi qui tempore pariatur modi ut. Aut quis quod ipsa expedita consequuntur aliquam ut facere.',
    title: 'Contact with powered kitchen appliance',
    year: 1972,
  },
  {
    id: 66,
    isbn: 'BZN5RTM4Z8GE20671',
    author: 41,
    edition: 4,
    format: 6,
    language: 21,
    genre: 10,
    pages: 232,
    publisher: 19,
    summary:
      'Culpa minima ipsam quibusdam quidem rerum. Tempora aut illum. Nemo perferendis nisi qui consectetur et nemo. Et quo quam sequi eveniet non. Ab laboriosam ratione sed laudantium sit incidunt et dolor sunt. Tempora beatae quia rem.',
    title: 'Subacute osteomyelitis, right tibia and fibula',
    year: 1954,
  },
  {
    id: 67,
    isbn: '25885071V3BZ67564',
    author: 3,
    edition: 3,
    format: 7,
    language: 20,
    genre: 15,
    pages: 127,
    publisher: 34,
    summary: 'voluptas',
    title: 'Chronic superficial gastritis without bleeding',
    year: 1956,
  },
  {
    id: 68,
    isbn: 'HVSVGCKZVXDH66518',
    author: 25,
    edition: 5,
    format: 8,
    language: 1,
    genre: 13,
    pages: 333,
    publisher: 28,
    summary: 'in voluptatem voluptates',
    title:
      'Burn of first degree of multiple sites of left shoulder and upper limb, except wrist and hand',
    year: 1937,
  },
  {
    id: 69,
    isbn: 'NN6XYA546PPU74497',
    author: 24,
    edition: 10,
    format: 9,
    language: 3,
    genre: 16,
    pages: 84,
    publisher: 35,
    summary:
      'Omnis sunt sapiente rem voluptatem rerum quos quia qui. Nisi doloremque vel soluta occaecati. Esse repellendus voluptas ut vero fuga in ullam voluptatum aspernatur. Consectetur accusantium animi aspernatur illo et temporibus assumenda distinctio. Velit eos nihil quo neque fugiat.',
    title: 'Unspecified juvenile rheumatoid arthritis, hip',
    year: 1984,
  },
  {
    id: 70,
    isbn: 'KZ3UX7UAY0BP42597',
    author: 45,
    edition: 4,
    format: 10,
    language: 11,
    genre: 26,
    pages: 548,
    publisher: 37,
    summary:
      'Ut a laborum doloribus. Consequatur ducimus quasi. Beatae nesciunt consequatur consequuntur enim. Dolorem odio nihil officiis voluptates consequatur quia qui ducimus provident.',
    title:
      'Aspiration of fluid as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure',
    year: 1996,
  },
  {
    id: 71,
    isbn: '1ZVT5YPZDDSF60330',
    author: 4,
    edition: 3,
    format: 1,
    language: 16,
    genre: 4,
    pages: 365,
    publisher: 12,
    summary: 'culpa',
    title: 'Acute mastoiditis without complications, unspecified ear',
    year: 1973,
  },
  {
    id: 72,
    isbn: '3Y3XLZ153FDB49124',
    author: 15,
    edition: 3,
    format: 2,
    language: 22,
    genre: 14,
    pages: 394,
    publisher: 18,
    summary:
      'Ut delectus amet numquam quo quod repudiandae neque rerum. Est qui nulla odit voluptatem ea itaque dignissimos sed. Deleniti qui et et facilis exercitationem quis consequatur.',
    title: 'Displaced trimalleolar fracture of left lower leg',
    year: 1926,
  },
  {
    id: 73,
    isbn: 'FHVN42D555UL92040',
    author: 27,
    edition: 6,
    format: 3,
    language: 7,
    genre: 17,
    pages: 178,
    publisher: 26,
    summary: 'sit ut officia',
    title:
      'Malignant neoplasm of overlapping sites of other and unspecified parts of mouth',
    year: 1950,
  },
  {
    id: 74,
    isbn: 'D7CZ1C0EN6T254064',
    author: 47,
    edition: 4,
    format: 4,
    language: 14,
    genre: 29,
    pages: 401,
    publisher: 27,
    summary:
      'Nihil facere sint velit. Praesentium quam distinctio tempora exercitationem esse hic quibusdam temporibus. Consequuntur fugit amet consequatur consequatur est sunt omnis quisquam reprehenderit.',
    title: 'Hereditary lymphedema',
    year: 1942,
  },
  {
    id: 75,
    isbn: 'M7NNRNHTM9GZ20455',
    author: 40,
    edition: 5,
    format: 5,
    language: 20,
    genre: 9,
    pages: 631,
    publisher: 34,
    summary: 'Hic voluptatum ea deleniti eius et.',
    title: 'Acute hepatitis A',
    year: 1942,
  },
  {
    id: 76,
    isbn: '6UJSVX6438AD15776',
    author: 15,
    edition: 10,
    format: 6,
    language: 8,
    genre: 10,
    pages: 86,
    publisher: 2,
    summary:
      'Quis odio reprehenderit eos sed ut. Enim aut culpa corporis. Earum non sint illo sunt libero eos. Inventore ullam odio ducimus voluptatem molestias. Id ut sit. In sunt tenetur excepturi non debitis est doloribus quos ut.\n \nQui non consequatur perspiciatis blanditiis cupiditate. Quaerat nostrum alias dolor minus maxime possimus nulla aliquid. Est deserunt iure. Molestiae saepe assumenda ut nulla corporis odio consequuntur. Exercitationem voluptatem impedit neque iusto consectetur.\n \nCupiditate excepturi atque aut quis labore impedit unde veritatis. Est optio voluptate consequatur et iusto repudiandae ducimus atque. Aut eos unde dolor expedita esse velit. Voluptas qui et dolorum aut aspernatur. Est ut omnis.',
    title:
      'Laceration with foreign body of unspecified eyelid and periocular area',
    year: 2006,
  },
  {
    id: 77,
    isbn: 'FBSB5WJTAGHR93530',
    author: 26,
    edition: 2,
    format: 7,
    language: 26,
    genre: 13,
    pages: 441,
    publisher: 22,
    summary: 'qui',
    title: 'Transient synovitis, hip',
    year: 1965,
  },
  {
    id: 78,
    isbn: 'U64LGKDVHCFC82736',
    author: 45,
    edition: 6,
    format: 8,
    language: 9,
    genre: 28,
    pages: 396,
    publisher: 27,
    summary:
      'Vel omnis sed quo dolorem earum assumenda sed.\nVoluptatum consequatur ipsum.\nNesciunt commodi eveniet cumque.\nAut accusantium velit maiores enim voluptas dolorem aperiam.',
    title: 'Burn of unspecified degree of upper back',
    year: 2009,
  },
  {
    id: 79,
    isbn: 'J4GU0SRJTHFZ11273',
    author: 1,
    edition: 4,
    format: 9,
    language: 10,
    genre: 11,
    pages: 511,
    publisher: 23,
    summary: 'Officia suscipit sint.',
    title: 'Meningococcal myocarditis',
    year: 1906,
  },
  {
    id: 80,
    isbn: 'GDNL6JXH3YYV19662',
    author: 41,
    edition: 4,
    format: 10,
    language: 7,
    genre: 28,
    pages: 476,
    publisher: 10,
    summary: 'Odit cupiditate rerum voluptate et aperiam vel.',
    title:
      'Pedestrian on skateboard injured in collision with pedal cycle, unspecified whether traffic or nontraffic accident',
    year: 1991,
  },
  {
    id: 81,
    isbn: '9R3CKE8K0ZD425115',
    author: 27,
    edition: 5,
    format: 1,
    language: 2,
    genre: 8,
    pages: 369,
    publisher: 31,
    summary:
      'Dolore ab corrupti ab modi. Voluptatibus doloribus beatae distinctio omnis consequatur laborum soluta pariatur. Sed facilis soluta dolor distinctio voluptate vero. Quisquam id nihil exercitationem porro officiis velit quae.\n \nQuae nemo sit quos amet animi praesentium. Facilis expedita consectetur quas iusto dolore quos ipsum praesentium. Fugit ratione exercitationem ut. Occaecati iusto quo recusandae repellat sint possimus. Nemo velit omnis occaecati incidunt rerum recusandae amet corrupti.\n \nExcepturi porro dolorem aut commodi repellendus. Voluptas odit ad. Animi nulla vitae laudantium perferendis earum minus.',
    title: 'Subluxation of lens, unspecified eye',
    year: 1912,
  },
  {
    id: 82,
    isbn: 'Z4HNYF2VFANB50881',
    author: 9,
    edition: 4,
    format: 2,
    language: 24,
    genre: 24,
    pages: 406,
    publisher: 24,
    summary:
      'Maiores velit quia. Labore dolore pariatur ullam ducimus. Numquam voluptatum consequuntur dolorum impedit aliquam tempore. Quia ut autem non iste odio.',
    title: 'Osteonecrosis in diseases classified elsewhere, thigh',
    year: 1985,
  },
  {
    id: 83,
    isbn: '20TNT19FYZSW57855',
    author: 36,
    edition: 8,
    format: 3,
    language: 23,
    genre: 4,
    pages: 429,
    publisher: 20,
    summary:
      'Ea ut cum maxime et adipisci totam a architecto et. Neque qui excepturi doloremque. Qui maxime velit voluptatem tenetur minus architecto aut.\n \nIncidunt sint pariatur. Sapiente modi et voluptatem magni maxime ut. Officia vitae sequi voluptatum laboriosam harum qui. Et voluptatem illo sequi sit ipsam accusantium pariatur. Error enim officia expedita eos asperiores et consequatur cum.\n \nIure doloribus nam maiores libero voluptates dicta quo sunt nesciunt. Neque exercitationem ut nesciunt. Et illo fugit aut voluptatum. Occaecati molestiae alias culpa odit non repellendus cum. Dolorem earum amet delectus necessitatibus iste ad.',
    title: 'Unspecified corneal deposit, unspecified eye',
    year: 1941,
  },
  {
    id: 84,
    isbn: '124RASWGLYA633277',
    author: 19,
    edition: 5,
    format: 4,
    language: 25,
    genre: 7,
    pages: 462,
    publisher: 5,
    summary: 'enim alias vel',
    title: 'Edema of left upper eyelid',
    year: 1935,
  },
  {
    id: 85,
    isbn: '9DFEHG9UVLD663308',
    author: 43,
    edition: 4,
    format: 5,
    language: 25,
    genre: 21,
    pages: 28,
    publisher: 15,
    summary:
      'Eligendi debitis fugit ut quas natus impedit. Dolorem vel itaque laboriosam sit suscipit quae non alias omnis. Sed ipsam possimus est omnis nemo expedita sint velit illum. Vero vel aut animi. Quis non fuga quam sit quo. Voluptatem vel blanditiis non corrupti necessitatibus voluptates.\n \nDolores quaerat in. Qui quia explicabo. Voluptatibus voluptas dignissimos totam quia qui laboriosam quisquam. Tempore aut ut omnis quo veniam consequuntur rerum. Dolores ea dolor autem voluptatibus consequatur non.\n \nNatus rerum velit et architecto deleniti. Qui fugiat recusandae veritatis nihil. Nesciunt dolorem ut iste placeat quia doloremque ut soluta dignissimos. Odio dolorem fugit.',
    title: 'Other spondylosis',
    year: 2011,
  },
  {
    id: 86,
    isbn: 'CKSJY3S5P8EM67816',
    author: 25,
    edition: 9,
    format: 6,
    language: 13,
    genre: 27,
    pages: 275,
    publisher: 34,
    summary:
      'Eum et aspernatur officia aperiam et consectetur voluptatem ut.',
    title: 'Periapical abscess without sinus',
    year: 1988,
  },
  {
    id: 87,
    isbn: 'HBNZM96B6RNA39479',
    author: 26,
    edition: 4,
    format: 7,
    language: 5,
    genre: 11,
    pages: 370,
    publisher: 37,
    summary: 'totam voluptatem magni',
    title: 'Other ulcerative colitis with intestinal obstruction',
    year: 2021,
  },
  {
    id: 88,
    isbn: 'M6FPN9MNF2C862205',
    author: 37,
    edition: 8,
    format: 8,
    language: 15,
    genre: 25,
    pages: 162,
    publisher: 16,
    summary:
      'Minima officia eum ullam delectus repellendus. Magnam distinctio soluta sed. Repellat cum nemo quo. Accusamus dolorem voluptatibus voluptas provident ipsum laudantium adipisci facilis qui.',
    title: 'Abnormal hard tissue formation in pulp',
    year: 1903,
  },
  {
    id: 89,
    isbn: 'DWT42Y01LZKW96272',
    author: 15,
    edition: 8,
    format: 9,
    language: 16,
    genre: 4,
    pages: 320,
    publisher: 10,
    summary:
      'Inventore ducimus officia id est vero repudiandae minima. Amet consequuntur quidem. Occaecati deserunt voluptatem nam dolor. Est quae perspiciatis alias alias. Laborum ratione sunt quis aspernatur officia deserunt laborum blanditiis. Voluptate est qui autem molestiae rerum iusto voluptatum.\n \nFacere sequi quia laboriosam vitae ratione itaque dolore. In aliquam quo voluptatibus error eaque inventore quam vero eveniet. Ab dolores sed sed eos eaque repellat laborum dignissimos velit.\n \nDelectus ducimus est quibusdam aut ea veniam ut unde. Et alias dolore deserunt libero omnis et. Minus aliquid natus optio qui.',
    title: 'Diffuse cystic mastopathy of unspecified breast',
    year: 2011,
  },
  {
    id: 90,
    isbn: 'M8U52EUSWSSV72102',
    author: 41,
    edition: 4,
    format: 10,
    language: 13,
    genre: 32,
    pages: 490,
    publisher: 31,
    summary:
      'In aliquid nihil minima. Eligendi nesciunt ut. Nihil provident nostrum quae dolores in nihil.',
    title: 'Burn of unspecified body region, unspecified degree',
    year: 1900,
  },
  {
    id: 91,
    isbn: 'KVSCPMUPDFYJ97499',
    author: 11,
    edition: 5,
    format: 1,
    language: 20,
    genre: 31,
    pages: 410,
    publisher: 32,
    summary:
      'Explicabo quae nihil.\nDeleniti inventore est blanditiis qui soluta.\nPorro tempora velit odit eligendi illum ut qui qui.',
    title: 'Complications of anesthesia during labor and delivery',
    year: 1902,
  },
  {
    id: 92,
    isbn: '99TJT8RPXZTT93844',
    author: 27,
    edition: 8,
    format: 2,
    language: 7,
    genre: 30,
    pages: 35,
    publisher: 30,
    summary: 'libero maxime perferendis',
    title: 'Chondromalacia, left wrist',
    year: 1928,
  },
  {
    id: 93,
    isbn: 'PS4P6427K8WX73781',
    author: 23,
    edition: 10,
    format: 3,
    language: 10,
    genre: 2,
    pages: 276,
    publisher: 36,
    summary:
      'Dolores provident laboriosam id voluptatum quaerat ut et repellat vitae.\nDoloremque cumque error eos voluptatem.\nEt eos reprehenderit.',
    title: 'Other spotted fevers',
    year: 1958,
  },
  {
    id: 94,
    isbn: 'UJ1EV5VP59BX81734',
    author: 50,
    edition: 9,
    format: 4,
    language: 21,
    genre: 1,
    pages: 514,
    publisher: 25,
    summary: 'et culpa ut',
    title: "Mooren's corneal ulcer, unspecified eye",
    year: 1927,
  },
  {
    id: 95,
    isbn: '59BMJAY9YBGV94549',
    author: 15,
    edition: 1,
    format: 5,
    language: 8,
    genre: 14,
    pages: 509,
    publisher: 13,
    summary:
      'Aut ut est sed pariatur enim eos. Recusandae nesciunt quo sunt. Vel fugiat necessitatibus voluptas.',
    title:
      'Bus occupant (driver) (passenger) injured in other specified transport accidents',
    year: 1902,
  },
  {
    id: 96,
    isbn: 'E3B3SV58ASSH92470',
    author: 16,
    edition: 1,
    format: 6,
    language: 22,
    genre: 7,
    pages: 65,
    publisher: 10,
    summary: 'facilis',
    title:
      'Strain of unspecified muscle and tendon at ankle and foot level',
    year: 1959,
  },
  {
    id: 97,
    isbn: 'FAWWJ8WR92U382680',
    author: 41,
    edition: 9,
    format: 7,
    language: 13,
    genre: 19,
    pages: 580,
    publisher: 42,
    summary: 'ut eveniet neque',
    title: 'Alcohol abuse with intoxication',
    year: 1981,
  },
  {
    id: 98,
    isbn: 'NU1BZNYNPHEB83190',
    author: 42,
    edition: 6,
    format: 8,
    language: 7,
    genre: 13,
    pages: 47,
    publisher: 13,
    summary:
      'Eos totam deserunt magni qui et. Reprehenderit et omnis cum maxime. Incidunt voluptatibus dolores eligendi.',
    title: 'Preterm labor without delivery, unspecified trimester',
    year: 1966,
  },
  {
    id: 99,
    isbn: 'RGFW93G0KMUT47086',
    author: 28,
    edition: 9,
    format: 9,
    language: 21,
    genre: 24,
    pages: 6,
    publisher: 38,
    summary:
      'Minima aut repellat eos nihil ullam suscipit blanditiis voluptates quae. Ipsum assumenda sequi ea enim vel. Voluptas asperiores est.',
    title: 'Glycogen storage disease, unspecified',
    year: 1992,
  },
  {
    id: 100,
    isbn: 'RF5EVDAHHNZZ16910',
    author: 50,
    edition: 9,
    format: 10,
    language: 26,
    genre: 12,
    pages: 540,
    publisher: 11,
    summary:
      'Itaque voluptatem deleniti modi aut commodi incidunt quibusdam beatae.',
    title: 'Unspecified dementia',
    year: 1981,
  },
];

// http://localhost:8081/titles?genres=1&formats=1,2,3,4&languages=1,2,3,4,5&order_by=-id
const data_filters = {
  formats: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  languages: [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
  ],
  genres: [
    1,
    2,
    3,
    4,
    5,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
  ],
};

const genre_values = [1];
const format_values = [1];
const language_values = [];

const filter_genres = (active) => ({ genre }) => {
  if (!genre_values.length) return true;
  if (active) {
    return genre_values.includes(genre);
  }
  return true;
};
const filter_languages = (active) => ({ language }) => {
  if (!language_values.length) return true;
  if (active) {
    return language_values.includes(language);
  }
  return true;
};
const filter_formats = (active) => ({ format }) => {
  if (!format_values.length) return true;
  if (active) {
    return format_values.includes(format);
  }
  return true;
};

const result = data
  .filter(filter_genres(true))
  .filter(filter_languages(true))
  .filter(filter_formats(true));

const formats = () =>
  genre_values.length === 0 && language_values.length === 0
    ? data_filters.formats
    : [
        ...new Set(
          result.map(({ format }) => format).sort((a, b) => a - b)
        ),
      ];

const languages = () =>
  format_values.length === 0 && genre_values.length === 0
    ? data_filters.languages
    : [
        ...new Set(
          result.map(({ language }) => language).sort((a, b) => a - b)
        ),
      ];

const genres = () =>
  format_values.length === 0 && language_values.length === 0
    ? data_filters.genres
    : [
        ...new Set(
          result.map(({ genre }) => genre).sort((a, b) => a - b)
        ),
      ];

console.log({
  results: result.length,
  active_filters: {
    formats: format_values,
    languages: language_values,
    genres: genre_values,
  },
  data_filters: {
    formats: formats(),
    languages: languages(),
    genres: genres(),
  },
});

// {
//   results: 3,
//   active_filters: { formats: [], languages: [], genres: [ 7 ] },
//   data_filters: {
//     formats: [ 1, 4, 6 ],
//     languages: [ 3, 22, 25 ],
//     genres: [
//        1,  2,  3,  4,  5,  7,  8,  9, 10,
//       11, 12, 13, 14, 15, 16, 17, 18, 19,
//       20, 21, 22, 23, 24, 25, 26, 27, 28,
//       29, 30, 31, 32
//     ]
//   }
// }
//
// {
//   results: 6,
//   active_filters: { formats: [], languages: [ 3 ], genres: [] },
//   data_filters: {
//     formats: [ 1, 2, 4, 9, 10 ],
//     languages: [
//        1,  2,  3,  4,  5,  6,  7,  8,
//        9, 10, 11, 12, 13, 14, 15, 16,
//       17, 18, 19, 20, 21, 22, 23, 24,
//       25, 26
//     ],
//     genres: [ 7, 16, 19, 24, 28 ]
//   }
// }
//
// RESULT:
// {
//   results: 1,
//   active_filters: { formats: [], languages: [ 3 ], genres: [ 7 ] },
//   data_filters: { formats: [ 1 ], languages: [ 3 ], genres: [ 7 ] }
// }
// SHOULD BE:
// {
//   results: 1,
//   active_filters: { formats: [], languages: [ 3 ], genres: [ 7 ] },
//   data_filters: {
//      formats: [ 1, 4 ],
//      languages: [ 3, 22, 25 ],
//      genres: [ 7, 16, 19, 24, 28 ]
//    }
// }
//
//
// EACH LANGUAGE has a set of formats and genres
// EACH GENRE has a set of formats and languages
// EACH FORMAT has a set o languages and genres
//
// For example
//
// genres: [ 1 ]
//  => formats: [ 2, 4, 5 ],
//  => languages: [ 1, 8, 17, 21 ],
// formats: [ 1 ]
//  => languages: [ 2, 3, 9, 16, 20, 25 ],
//  => genres: [ 4, 7, 8, 14, 15, 17, 22, 27, 28, 31 ]
// languages: [ 1 ]
//  => formats: [ 2, 4, 5, 8, 10 ],
//  => genres: [ 1, 2, 13, 17, 19 ]
